version: '3.8'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./azurite_data:/data
    command: "azurite-blob --blobHost 0.0.0.0 --loose"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/devstoreaccount1"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:15
    container_name: postgres_b3
    environment:
      # As variáveis agora vêm do arquivo .env
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432" # Porta também pode ser lida do .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: